name: Go
on:
  push:
    branches:
      - "*"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - run: make bootstrap-tools
    - run: make lint
    - run: make cover

    - uses: codecov/codecov-action@v1
